name: "crypto_tracker"

services:
  rails-app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile

    tty: true
    stdin_open: true

    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      - HISTFILE=/home/rails/crypto-tracker/tmp/.bash_history
      - HISTSIZE=10000
      - SAVEHIST=10000
      - CAPYBARA_SERVER_PORT=45678
      - SELENIUM_HOST=selenium
      - REDIS_URL=redis://redis:6379/1
      - KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD
      - DB_HOST=postgres

    ports:
      - "3000:3000"

    volumes:
      - ../:/app
      - ../crypto-tracker/tmp/bundle:/usr/local/bundle
      - ../crypto-tracker/tmp/node_modules:/app/crypto-tracker/node_modules
      - ../crypto-tracker/tmp/.bash_history:/home/rails/crypto-tracker/tmp/.bash_history

    working_dir: /app
    command: sleep infinity

    depends_on:
      - redis
      - postgres

  listener:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    environment:
      - RAILS_ENV=development
      - BUNDLE_PATH=/usr/local/bundle
      - HISTFILE=/home/rails/crypto-tracker/tmp/.bash_history
      - HISTSIZE=10000
      - SAVEHIST=10000
      - CAPYBARA_SERVER_PORT=45678
      - SELENIUM_HOST=selenium
      - REDIS_URL=redis://redis:6379/1
      - KAMAL_REGISTRY_PASSWORD=$KAMAL_REGISTRY_PASSWORD
      - DB_HOST=postgres
    volumes:
      - ../:/app
      - ../crypto-tracker/tmp/bundle:/usr/local/bundle
      - ../crypto-tracker/tmp/node_modules:/app/crypto-tracker/node_modules
      - ../crypto-tracker/tmp/.bash_history:/home/rails/crypto-tracker/tmp/.bash_history
    restart: on-failure
    working_dir: /app
    # This command will start our price listener service
    # command: sleep infinity
    command: bash -l -c "bin/setup --skip-server && bin/rails price_listener:run"
    depends_on:
      - redis
      - postgres
      - rails-app


  selenium:
    image: selenium/standalone-chromium
    restart: unless-stopped

  redis:
    image: redis:7.2
    restart: unless-stopped
    volumes:
    - redis-data:/data

  postgres:
    image: postgres:16.1
    restart: unless-stopped
    networks:
    - default
    volumes:
    - postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
  redis-data:
  postgres-data:
